"""
This type stub file was generated by pyright.
"""

import numpy as np
import torch
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

"""Readable staged video-to-video API for StreamDiffusionV2."""
SingleMode = Literal["single", "single-wo"]
@dataclass
class VideoChunk:
    """One video chunk prepared for the encode -> denoise -> decode loop."""
    frames: torch.Tensor
    start_idx: int
    end_idx: int
    current_start: int
    current_end: int
    ...


@dataclass
class EncodedChunk:
    """Encoded latent chunk plus the schedule metadata needed for denoising."""
    noisy_latents: torch.Tensor
    current_start: int
    current_end: int
    noise_scale: float
    current_step: int | None = ...


@dataclass
class DenoisedChunk:
    """Denoised latent chunk ready for VAE decoding."""
    denoised_pred: torch.Tensor
    last_frame_only: bool
    ...


def load_video(video_path: str, *, height: int = ..., width: int = ...) -> torch.Tensor:
    """Load a video file as a normalized tensor with shape [C, T, H, W]."""
    ...

def export_video(video: np.ndarray, output_path: str, *, fps: int = ...) -> str:
    """Write a `[T, H, W, C]` float video array to an mp4 file."""
    ...

class StreamDiffusionV2Pipeline:
    """Readable staged single-GPU API that mirrors the offline inference flow."""
    def __init__(self, checkpoint_folder: str, *, mode: SingleMode = ..., config_path: str | None = ..., prompt_cache_dir: str | None = ..., device: str | torch.device | None = ..., noise_scale: float = ..., height: int = ..., width: int = ..., fps: int = ..., step: int = ..., seed: int = ..., model_type: str = ..., use_taehv: bool = ..., use_tensorrt: bool = ..., fast: bool = ..., profile: bool = ...) -> None:
        ...
    
    def close(self) -> None:
        ...
    
    def __enter__(self) -> StreamDiffusionV2Pipeline:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        ...
    
    def enable_acceleration(self, *, use_taehv: bool = ..., use_tensorrt: bool = ..., fast: bool = ...) -> StreamDiffusionV2Pipeline:
        """Rebuild the pipeline with the requested acceleration flags."""
        ...
    
    def prepare(self, prompt: str) -> None:
        """Reset the stream state and store the prompt for the next denoising pass."""
        ...
    
    def chunk_video(self, video: str | Path | torch.Tensor) -> list[VideoChunk]:
        """Split a full input video into the same chunks used by the offline inference loop."""
        ...
    
    @torch.inference_mode()
    def encode_chunk(self, input_video: str | Path | torch.Tensor, chunk: VideoChunk, *, previous_noise_scale: float | None = ..., initial_noise_scale: float | None = ...) -> EncodedChunk:
        """Encode one chunk in the same style as the offline inference loop."""
        ...
    
    @torch.inference_mode()
    def encode_video(self, video: str | Path | torch.Tensor) -> list[EncodedChunk]:
        """Encode a full input video into noisy latent chunks."""
        ...
    
    @torch.inference_mode()
    def denoise_chunks(self, chunks: list[EncodedChunk]) -> list[DenoisedChunk]:
        """Run DiT denoising over the encoded chunks."""
        ...
    
    @torch.inference_mode()
    def denoise_chunk(self, chunk: EncodedChunk) -> DenoisedChunk | None:
        """Run DiT on one encoded chunk and return a decodable latent when available."""
        ...
    
    @torch.inference_mode()
    def decode_chunks(self, chunks: list[DenoisedChunk]) -> np.ndarray:
        """Decode denoised latent chunks into a `[T, H, W, C]` video array."""
        ...
    
    @torch.inference_mode()
    def decode_chunk(self, chunk: DenoisedChunk) -> np.ndarray:
        """Decode one denoised latent chunk into `[T, H, W, C]` frames."""
        ...
    
    @torch.inference_mode()
    def __call__(self, video: str | Path | torch.Tensor) -> np.ndarray:
        """Run the full staged pipeline after `prepare(prompt)` has been called."""
        ...
    


